In [ ]:
import nltk
nltk.download('all')

In [5]:
corpus='''I'm Pooja and I'm here to teach NLP to the students and they seem eager to learn this topic.
It's a four hour lecture which occurs on every Tuesday'''

In [12]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize


In [7]:
sent_tokenize(corpus)

["I'm Pooja and I'm here to teach NLP to the students and they seem eager to learn this topic.",
 "It's a four hour lecture which occurs on every Tuesday"]

In [ ]:
word_tokenize(corpus)

In [15]:
from nltk.tokenize import

In [2]:
text = '''Beans. I was trying to explain to somebody as we were flying in, that’s corn.  That’s beans. And they were very impressed at my agricultural knowledge. Please give it up for Amaury once again for that outstanding introduction. I have a bunch of good friends here today, including somebody who I served with, who is one of the finest senators in the country, and we’re lucky to have him, your Senator, Dick Durbin is here. I also noticed, by the way, former Governor Edgar here, who I haven’t seen in a long time, and somehow he has not aged and I have. And it’s great to see you, Governor. I want to thank President Killeen and everybody at the U of I System for making it possible for me to be here today. And I am deeply honored at the Paul Douglas Award that is being given to me. He is somebody who set the path for so much outstanding public service here in Illinois. Now, I want to start by addressing the elephant in the room. I know people are still wondering why I didn’t speak at the commencement.'''

In [3]:
# Python3 code for preprocessing text 
import nltk 
import re 
import numpy as np 
  
# execute the text here as : 
# text = """ # place text here  """ 
dataset = nltk.sent_tokenize(text) 
for i in range(len(dataset)): 
    dataset[i] = dataset[i].lower() 
    dataset[i] = re.sub(r'\W', ' ', dataset[i]) 
    dataset[i] = re.sub(r'\s+', ' ', dataset[i]) 

In [5]:
dataset[i]

'i know people are still wondering why i didn t speak at the commencement '

In [7]:
from nltk.stem import PorterStemmer
from nltk import sent_tokenize

In [10]:
Corpus = 'People should learn to respect others. Give and take respect policy shoul be followed'

sent=sent_tokenize(Corpus)

In [11]:
print(sent)

['People should learn to respect others.', 'Give and take respect policy shoul be followed']


In [14]:
ps=PorterStemmer()

Stem=ps.stem('Establishment')

In [15]:
print(Stem)

establish


In [23]:
ps=PorterStemmer()

In [26]:
words= ['Connecting','Establishing','Requirement','Punishment']
lower= [word.lower() for word in words]
for w in lower:
    stemmedword=ps.stem(w)
    #sent_tokenize(w)
    print(w,":->", stemmedword)

connecting :-> connect
establishing :-> establish
requirement :-> requir
punishment :-> punish


In [27]:
from nltk.corpus import stopwords

In [29]:
corpus='''The stock market is highly volatile these days. 
Many investors are looking for the best opportunities, but they should be cautious before making any decisions. 
********It is important to analyze trends and patterns before investing large amounts of money in stocks.'''

sw=stopwords.words('english')

In [ ]:
sw


In [ ]:
#OneHotEncoding in Machine Learning, It converts categorical data into binary form.It functions by representing each category in feature as binary vectors of 1s an 0s with vector size equivalent to number of potential categories.

#'''In Sentiment analysis assignment for example, we describe each word in a sentence as One Hot Encoded vector and use these vector as input to forecast the sentiment of the sentence.

#The quick brown fox jumps over the lazy dog
#She sells seashells by the seashore.
#Peter Piper picked a peck of pickled pipers

# Step 1: Each word in the phrase should be used as single compressed vectors
# Step 2: Determine the distinct word in the sentence to calculate the number of potential categories
# Step 3: In the above category, OneHotEncoding will show 18 potential categories.

import numpy as np
#Define a corpus

corpus=["The The quick brown fox jumps over the lazy dog",
            "She sells seashells by the seashore.",
         "Peter Piper picked a peck of pickled pipers"]

#Create a set of unique words in the corpus

unique_words = set()
for sentence in corpus:
    #Split the sentence and convert the word to lower
    for word in sentence.split():
        unique_words.add(word.lower())
    #Create an index to map each unique word to an index
    #Create a dictionary to map each word to an index
word_to_index = {}
for i, word in enumerate(unique_words):
        word_to_index[word] = i
    
    #Create one hot encoded vector for each word in the corpus
one_hot_vectors=[]

for sentence in corpus:
        sentence_vectors = []
        for word in sentence.split():
            vector=np.zeros(len(unique_words))
            vector[word_to_index[word.lodwer()]] = 1
            sentence_vectors.append(vector)
        one_hot_vectors.append(sentence_vectors)

#Print the one hot encoded vectors 
for vector in one_hot_vectors[0]:
    print(vector)


 










[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np

# Define the corpus of text
corpus = ["The quick brown fox jumped over the lazy dog.",
	"She sells seashells by the seashore.",
	"Peter Piper picked a peck of pickled peppers."]

# Create a set of unique words in the corpus
unique_words = set()
for sentence in corpus:
	for word in sentence.split():
		unique_words.add(word.lower())

# Create a dictionary to map each
# unique word to an index
word_to_index = {}
for i, word in enumerate(unique_words):
	word_to_index[word] = i

# Create one-hot encoded vectors for
# each word in the corpus
one_hot_vectors = []
for sentence in corpus:
	sentence_vectors = []
	for word in sentence.split():
		vector = np.zeros(len(unique_words))
		vector[word_to_index[word.lower()]] = 1
		sentence_vectors.append(vector)
	one_hot_vectors.append(sentence_vectors)

# Print the one-hot encoded vectors 
# for the first sentence
print("One-hot encoded vectors for the first sentence:")
for vector in one_hot_vectors[0]:
	print(vector)



In [ ]:
#Word embeddings
#In NLP, word embedding is a term used for the representation of words for text analysis, typically in the
#form of real valued vectors that encodes the meaning of words for text analysis, typically in the form of real-valued
#vectors that encodes the meaning of the word such that the words that are closer in vector space are expected to be 
# similar in meaning. OHE, BOW and TF-IDF are all part of word embeddings.

In [ ]:
 #Word2Vec
 #Word2Vec is a technique for Natural Language processing published in 2013. The Word2Vec is a algorithm uses a neural network moel to learn words associated from
#large corpus of text. Once trained, such a model can detect synonyms words or suggest additional words for a partial sentence.
#As the name implies, word2vec represents each distinct words with a partial list of numbers called as vector.