In [22]:
import nltk
nltk.download('all')

[nltk_data] Error loading all: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


False

In [26]:
corpus='''I'm Pooja and I'm here to learn NLP from the mentors and people seem eager to learn this topic.
There is lot research going on for the same'''

In [24]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize


In [27]:
sent_tokenize(corpus)

["I'm Pooja and I'm here to learn NLP from the mentors and people seem eager to learn this topic.",
 'There is lot research going on for the same']

In [ ]:
word_tokenize(corpus)

In [15]:
from nltk.tokenize import

In [12]:
text = '''I am stuying in thir sem.'''

In [13]:
# Python3 code for preprocessing text 
import nltk 
import re 
import numpy as np 
  
# execute the text here as : 
# text = """ # place text here  """ 
dataset = nltk.sent_tokenize(text) 
for i in range(len(dataset)): 
    dataset[i] = dataset[i].lower() 
    dataset[i] = re.sub(r'\W', ' ', dataset[i]) 
    dataset[i] = re.sub(r'\s+', ' ', dataset[i]) 

In [14]:
dataset[i]

'i am stuying in thir sem '

In [7]:
from nltk.stem import PorterStemmer
from nltk import sent_tokenize

In [10]:
Corpus = 'People should learn to respect others. Give and take respect policy shoul be followed'

sent=sent_tokenize(Corpus)

In [11]:
print(sent)

['People should learn to respect others.', 'Give and take respect policy shoul be followed']


In [14]:
ps=PorterStemmer()

Stem=ps.stem('Establishment')

In [15]:
print(Stem)

establish


In [23]:
ps=PorterStemmer()

In [26]:
words= ['Connecting','Establishing','Requirement','Punishment']
lower= [word.lower() for word in words]
for w in lower:
    stemmedword=ps.stem(w)
    #sent_tokenize(w)
    print(w,":->", stemmedword)

connecting :-> connect
establishing :-> establish
requirement :-> requir
punishment :-> punish


In [27]:
from nltk.corpus import stopwords

In [15]:
corpus='''The stock market is highly volatile these days. 
Many investors are looking for the best opportunities, but they should be cautious before making any decisions. 
********It is important to analyze trends and patterns before investing large amounts of money in stocks.'''

sw=stopwords.words('english')

In [ ]:
sw


In [ ]:
#OneHotEncoding in Machine Learning, It converts categorical data into binary form.It functions by representing each category in feature as binary vectors of 1s an 0s with vector size equivalent to number of potential categories.

#'''In Sentiment analysis assignment for example, we describe each word in a sentence as One Hot Encoded vector and use these vector as input to forecast the sentiment of the sentence.

#The quick brown fox jumps over the lazy dog
#She sells seashells by the seashore.
#Peter Piper picked a peck of pickled pipers

# Step 1: Each word in the phrase should be used as single compressed vectors
# Step 2: Determine the distinct word in the sentence to calculate the number of potential categories
# Step 3: In the above category, OneHotEncoding will show 18 potential categories.

import numpy as np
#Define a corpus

corpus=["The The quick brown fox jumps over the lazy dog",
            "She sells seashells by the seashore.",
         "Peter Piper picked a peck of pickled pipers"]

#Create a set of unique words in the corpus

unique_words = set()
for sentence in corpus:
    #Split the sentence and convert the word to lower
    for word in sentence.split():
        unique_words.add(word.lower())
    #Create an index to map each unique word to an index
    #Create a dictionary to map each word to an index
word_to_index = {}
for i, word in enumerate(unique_words):
        word_to_index[word] = i
    
    #Create one hot encoded vector for each word in the corpus
one_hot_vectors=[]

for sentence in corpus:
        sentence_vectors = []
        for word in sentence.split():
            vector=np.zeros(len(unique_words))
            vector[word_to_index[word.lodwer()]] = 1
            sentence_vectors.append(vector)
        one_hot_vectors.append(sentence_vectors)

#Print the one hot encoded vectors 
for vector in one_hot_vectors[0]:
    print(vector)


 










[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
import numpy as np

# Define the corpus of text
corpus = ["The quick brown fox jumped over the lazy dog.",
	"She sells seashells by the seashore.",
	"Peter Piper picked a peck of pickled peppers."]

# Create a set of unique words in the corpus
unique_words = set()
for sentence in corpus:
	for word in sentence.split():
		unique_words.add(word.lower())

# Create a dictionary to map each
# unique word to an index
word_to_index = {}
for i, word in enumerate(unique_words):
	word_to_index[word] = i

# Create one-hot encoded vectors for
# each word in the corpus
one_hot_vectors = []
for sentence in corpus:
	sentence_vectors = []
	for word in sentence.split():
		vector = np.zeros(len(unique_words))
		vector[word_to_index[word.lower()]] = 1
		sentence_vectors.append(vector)
	one_hot_vectors.append(sentence_vectors)

# Print the one-hot encoded vectors 
# for the first sentence
print("One-hot encoded vectors for the first sentence:")
for vector in one_hot_vectors[0]:
	print(vector)



One-hot encoded vectors for the first sentence:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#Disavantages of OHE
#1.

In [ ]:
#Word embeddings
#In NLP, word embedding is a term used for the representation of words for text analysis, typically in the
#form of real valued vectors that encodes the meaning of words for text analysis, typically in the form of real-valued
#vectors that encodes the meaning of the word such that the words that are closer in vector space are expected to be 
# similar in meaning. OHE, BOW and TF-IDF are all part of word embeddings.

In [ ]:
 #Word2Vec
 #Word2Vec is a technique for Natural Language processing published in 2013. The Word2Vec is a algorithm uses a neural network moel to learn words associated from
#large corpus of text. Once trained, such a model can detect synonyms words or suggest additional words for a partial sentence.
#As the name implies, word2vec represents each distinct words with a partial list of numbers called as vector.

### BAG OF WORDS EXAMPLE

In [14]:
def vectorize(tokens):
    ''' This function takes list of words in a sentence as input 
    and returns a vector of size of filtered_vocab.It puts 0 if the 
    word is not present in tokens and count of token if present.'''
    vector=[]
    for w in filtered_vocab:
        vector.append(tokens.count(w))
    return vector
def unique(sequence):
    '''This functions returns a list in which the order remains 
    same and no item repeats.Using the set() function does not 
    preserve the original ordering,so i didnt use that instead'''
    seen = set()
    return [x for x in sequence if not (x in seen or seen.add(x))]
#create a list of stopwords.You can import stopwords from nltk too
stopwords=["to","is","a"]
#list of special characters.You can use regular expressions too
special_char=[",",":"," ",";",".","?"]
#Write the sentences in the corpus,in our case, just two 
string1="Welcome to Great Learning , Now start learning"
string2="Learning is a good practice"
#convert them to lower case
string1=string1.lower()
string2=string2.lower()
#split the sentences into tokens
tokens1=string1.split()
tokens2=string2.split()
print(tokens1)
print(tokens2)
#create a vocabulary list
vocab=unique(tokens1+tokens2)
print(vocab)
#filter the vocabulary list
filtered_vocab=[]
for w in vocab: 
    if w not in stopwords and w not in special_char: 
        filtered_vocab.append(w)
print(filtered_vocab)
#convert sentences into vectords
vector1=vectorize(tokens1)
print(vector1)
vector2=vectorize(tokens2)
print(vector2)

['welcome', 'to', 'great', 'learning', ',', 'now', 'start', 'learning']
['learning', 'is', 'a', 'good', 'practice']
['welcome', 'to', 'great', 'learning', ',', 'now', 'start', 'is', 'a', 'good', 'practice']
['welcome', 'great', 'learning', 'now', 'start', 'good', 'practice']
[1, 1, 2, 1, 1, 0, 0]
[0, 0, 1, 0, 0, 1, 1]


In [4]:
# Python3 code for preprocessing text 
import nltk 
import re 
import numpy as np 
  
# execute the text here as : 
# text = """ # place text here  """ 
dataset = nltk.sent_tokenize(text) 
for i in range(len(dataset)): 
    dataset[i] = dataset[i].lower() 
    dataset[i] = re.sub(r'\W', ' ', dataset[i]) 
    dataset[i] = re.sub(r'\s+', ' ', dataset[i]) 

In [6]:
print(dataset)

['beans ', 'i was trying to explain to somebody as we were flying in that s corn ', 'that s beans ', 'and they were very impressed at my agricultural knowledge ', 'please give it up for amaury once again for that outstanding introduction ', 'i have a bunch of good friends here today including somebody who i served with who is one of the finest senators in the country and we re lucky to have him your senator dick durbin is here ', 'i also noticed by the way former governor edgar here who i haven t seen in a long time and somehow he has not aged and i have ', 'and it s great to see you governor ', 'i want to thank president killeen and everybody at the u of i system for making it possible for me to be here today ', 'and i am deeply honored at the paul douglas award that is being given to me ', 'he is somebody who set the path for so much outstanding public service here in illinois ', 'now i want to start by addressing the elephant in the room ', 'i know people are still wondering why i d

In [7]:
# Creating the Bag of Words model 
word2count = {} 
for data in dataset: 
    words = nltk.word_tokenize(data) 
    for word in words: 
        if word not in word2count.keys(): 
            word2count[word] = 1
        else: 
            word2count[word] += 1

In [ ]:
word2count

In [ ]:
# In our model, we have a total of 118 words. However when processing large texts, the number of words could reach millions. We do not need to use all those words. Hence, we select a particular number of most frequently used words. To implement this we use:

In [10]:
import heapq 
freq_words = heapq.nlargest(100, word2count, key=word2count.get)

In [ ]:
freq_words


In [12]:
X = [] 
for data in dataset: 
    vector = [] 
    for word in freq_words: 
        if word in nltk.word_tokenize(data): 
            vector.append(1) 
        else: 
            vector.append(0) 
    X.append(vector) 
X = np.asarray(X) 

In [13]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0]])

### TF-IDF

In [ ]:
# tf(i,j)= n(i,j)/sum(n(i,j))
# IDF = 1+log(N/dN)

#N = Total number of documents in the dataset
#dN = total number of documents in which nth word occur

#TF-IDF=TF*IDF

In [ ]:
import numpy as np # For numerical operations - mean
import math # For mathematical operations - log
import fitz # from PyMuPDF for pdf file reading
import nltk # For natural language text processing

nltk.download('punkt') # For tokenization
nltk.download('stopwords') # For removing the stopwords after tokenization

from nltk.tokenize import sent_tokenize, word_tokenize # For tokenizing the text
from nltk.corpus import stopwords # For removing the stopwords

In [1]:
import nltk
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english')) 
text = '''I am is was were fruits, vegetables'''

In [19]:
# Example usage

words = text.split()
filtered_words = [word for word in words if word.lower() not in stop_words]

print("Original:", text)
print("After Stopword Removal:", " " .join(filtered_words))

Original: I am is was were fruits, vegetables
After Stopword Removal: fruits, vegetables


In [2]:
pip install gensim


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
#Gensim library is use in Word2vec

In [3]:
import gensim
import pandas as pd

In [4]:
df=pd.read_json("Cell_Phones_and_Accessories_5.json",lines=True)

In [5]:
df

reviewerID        asin       reviewerName helpful  \
0       A30TL5EWN6DFXT  120401325X          christina  [0, 0]   
1        ASY55RVNIL0UD  120401325X           emily l.  [0, 0]   
2       A2TMXE2AFO7ONB  120401325X              Erica  [0, 0]   
3        AWJ0WZQYMYFQ4  120401325X                 JM  [4, 4]   
4        ATX7CZYFXI1KW  120401325X   patrice m rogoza  [2, 3]   
...                ...         ...                ...     ...   
194434  A1YMNTFLNDYQ1F  B00LORXVUE    eyeused2loveher  [0, 0]   
194435  A15TX8B2L8B20S  B00LORXVUE       Jon Davidson  [0, 0]   
194436  A3JI7QRZO1QG8X  B00LORXVUE  Joyce M. Davidson  [0, 0]   
194437  A1NHB2VC68YQNM  B00LORXVUE     Nurse Farrugia  [0, 0]   
194438  A1AG6U022WHXBF  B00LORXVUE     Trisha Crocker  [0, 0]   

                                               reviewText  overall  \
0       They look good and stick good! I just don't li...        4   
1       These stickers work like the review says they ...        5   
2       These are awesome and make my phone look so st...        5   
3       Item arrived in great time and was in perfect ...        4   
4       awesome! stays on, and looks great. can be use...        5   
...                                                   ...      ...   
194434  Works great just like my original one. I reall...        5   
194435  Great product. Great packaging. High quality a...        5   
194436  This is a great cable, just as good as the mor...        5   
194437  I really like it becasue it works well with my...        5   
194438  product as described, I have wasted a lot of m...        5   

                                                  summary  unixReviewTime  \
0                                              Looks Good      1400630400   
1                                   Really great product.      1389657600   
2                                          LOVE LOVE LOVE      1403740800   
3                                                   Cute!      1382313600   
4               leopard home button sticker for iphone 4s      1359849600   
...                                                   ...             ...   
194434                           This works just perfect!      1405900800   
194435           Great replacement cable. Apple certified      1405900800   
194436                                       Real quality      1405900800   
194437  I really like it becasue it works well with my...      1405814400   
194438              I have wasted a lot of money on cords      1405900800   

         reviewTime  
0       05 21, 2014  
1       01 14, 2014  
2       06 26, 2014  
3       10 21, 2013  
4        02 3, 2013  
...             ...  
194434  07 21, 2014  
194435  07 21, 2014  
194436  07 21, 2014  
194437  07 20, 2014  
194438  07 21, 2014  

[194439 rows x 9 columns]

In [7]:
df.shape

(194439, 9)

In [6]:
review_text=df.reviewText.apply(gensim.utils.simple_preprocess)

In [7]:
review_text

0         [they, look, good, and, stick, good, just, don...
1         [these, stickers, work, like, the, review, say...
2         [these, are, awesome, and, make, my, phone, lo...
3         [item, arrived, in, great, time, and, was, in,...
4         [awesome, stays, on, and, looks, great, can, b...
                                ...                        
194434    [works, great, just, like, my, original, one, ...
194435    [great, product, great, packaging, high, quali...
194436    [this, is, great, cable, just, as, good, as, t...
194437    [really, like, it, becasue, it, works, well, w...
194438    [product, as, described, have, wasted, lot, of...
Name: reviewText, Length: 194439, dtype: object

In [8]:
review_text.loc[0]

['they',
 'look',
 'good',
 'and',
 'stick',
 'good',
 'just',
 'don',
 'like',
 'the',
 'rounded',
 'shape',
 'because',
 'was',
 'always',
 'bumping',
 'it',
 'and',
 'siri',
 'kept',
 'popping',
 'up',
 'and',
 'it',
 'was',
 'irritating',
 'just',
 'won',
 'buy',
 'product',
 'like',
 'this',
 'again']

In [9]:
df.reviewText.loc[0]

"They look good and stick good! I just don't like the rounded shape because I was always bumping it and Siri kept popping up and it was irritating. I just won't buy a product like this again"

In [10]:
#Training word 2 vector model

#Train the model for reviews. Use a window of size 10 i.e. 10 words before the present word and 10 words ahead. A sentence with at least 2 words should only be considered, configure this using min_count parameter.

#Workers define how many CPU threads to be used.



In [11]:
#Initialize the model
model = gensim.models.Word2Vec(window=10,min_count=2,workers=4)

In [12]:
#Build Vocabulary

model.build_vocab(review_text, progress_per=1000)

In [ ]:
#Train the word2vec model

model.train(review_text,total_examples=model.corpus_count,epochs= model.epochs)

(61505105, 83868975)

In [14]:
#Save the model
model.save("./word2vec-amazon-cell-accessories-reviews-short.model")

In [15]:
#Finding similar words and similarity between words

model.wv.most_similar("experience")

[('experiences', 0.7549813985824585),
 ('success', 0.5746661424636841),
 ('results', 0.5310482382774353),
 ('dissatisfaction', 0.5005948543548584),
 ('respect', 0.498167484998703),
 ('novice', 0.490531325340271),
 ('perspective', 0.48767054080963135),
 ('opinion', 0.48721110820770264),
 ('faith', 0.4846615791320801),
 ('impressions', 0.4831383526325226)]

In [ ]:

model.wv.similarity(w1="cheap",w2="inexpensive")

0.4406756

In [20]:
model.wv.similarity(w1="great", w2="perfect")

0.7207874